import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,SlidersHorizontal,Sparkles,Trophy,Database,Home as HomeIcon,Heart,ChevronRight} from 'lucide-react';
import './styles.css';

const ATTRS=['Đơn giản','Lộng lẫy','Thanh lịch','Năng động','Trưởng thành','Dễ thương','Gợi cảm','Kín đáo','Mát mẻ','Giữ ấm'];
const TYPES=['Tóc','Đầm','Áo','Quần','Giày','Sức','Trang điểm','Phụ kiện'];
const SOURCES=['Shop','Lầu Mộng Cảnh','Chế tạo','Tiến hóa','Sự kiện'];

const seed=[
{id:1,name:'Tóc Ánh Trăng',type:'Tóc',rarity:5,source:'Sự kiện',tags:['Thanh lịch','Mát mẻ'],score:9876},
{id:2,name:'Váy Hoa Ngọc',type:'Đầm',rarity:5,source:'Tiến hóa',tags:['Lộng lẫy','Dễ thương'],score:9821},
{id:3,name:'Giày Bạch Ngọc',type:'Giày',rarity:4,source:'Shop',tags:['Thanh lịch','Đơn giản'],score:9410},
{id:4,name:'Vương miện Tinh Vân',type:'Phụ kiện',rarity:5,source:'Sự kiện',tags:['Lộng lẫy','Trưởng thành'],score:9730},
{id:5,name:'Mắt Sao Băng',type:'Trang điểm',rarity:5,source:'Lầu Mộng Cảnh',tags:['Gợi cảm','Trưởng thành'],score:9688},
{id:6,name:'Áo Lavender',type:'Áo',rarity:4,source:'Chế tạo',tags:['Dễ thương','Kín đáo'],score:9180},
{id:7,name:'Quần Mộng Mơ',type:'Quần',rarity:4,source:'Sự kiện',tags:['Năng động','Mát mẻ'],score:9105},
{id:8,name:'Túi Ngọc Trai',type:'Phụ kiện',rarity:5,source:'Shop',tags:['Thanh lịch','Lộng lẫy'],score:9501}
];

function Layout({page,setPage,children}){return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setPage('home')}><span className="brand-mark">A</span><span>Aetheria</span></button><nav>{[['home','Trang chủ',HomeIcon],['database','Kho Item',Database],['arena','Khu thi đấu',Trophy]].map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={17}/>{label}</button>)}</nav></header><main>{children}</main><footer>Aetheria • Fanmade • Dữ liệu tham khảo cộng đồng và nguồn công khai</footer></div>}

function Home({setPage}){return <section className="hero-wrap"><div className="hero"><div><span className="eyebrow"><Sparkles size={15}/> THE STYLE ARCHIVE</span><h1>Chạm vào thế giới<br/><em>thời trang huyền ảo.</em></h1><p>Aetheria là kho tra cứu tiếng Việt dành cho Ngôi Sao Thời Trang VNG — tìm item, thuộc tính và khám phá gợi ý Khu Thi Đấu.</p><div className="hero-actions"><button className="primary" onClick={()=>setPage('database')}>Mở kho Item <ChevronRight size={17}/></button><button className="secondary" onClick={()=>setPage('arena')}>Xem Khu thi đấu</button></div></div><div className="orb"><Sparkles size={54}/><span>AETHERIA</span></div></div><div className="cards"><button onClick={()=>setPage('database')}><Database/><strong>Kho Item</strong><span>Tìm kiếm & lọc nhanh</span></button><button onClick={()=>setPage('arena')}><Trophy/><strong>Top 20</strong><span>Bảng xếp hạng theo chủ đề</span></button><button><Heart/><strong>Phối đồ</strong><span>Chuẩn bị trong roadmap</span></button></div></section>}

function Database(){const [q,setQ]=useState('');const [type,setType]=useState('Tất cả');const [source,setSource]=useState('Tất cả');const [attr,setAttr]=useState('Tất cả');const data=useMemo(()=>seed.filter(x=>(!q||x.name.toLowerCase().includes(q.toLowerCase()))&&(type==='Tất cả'||x.type===type)&&(source==='Tất cả'||x.source===source)&&(attr==='Tất cả'||x.tags.includes(attr))),[q,type,source,attr]);return <section className="page"><div className="page-head"><div><span className="eyebrow">DATABASE</span><h2>Kho Item</h2><p>Tra cứu thuộc tính, nguồn gốc và tag phong cách.</p></div><span className="count">{data.length} kết quả</span></div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên item..."/><SlidersHorizontal/></div><div className="filters"><select value={type} onChange={e=>setType(e.target.value)}><option>Tất cả</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select><select value={attr} onChange={e=>setAttr(e.target.value)}><option>Tất cả</option>{ATTRS.map(x=><option key={x}>{x}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option>Tất cả</option>{SOURCES.map(x=><option key={x}>{x}</option>)}</select></div><div className="grid">{data.map(x=><article className="item" key={x.id}><div className="item-art"><span>#{x.id}</span><Sparkles/></div><div className="item-body"><div className="item-title"><h3>{x.name}</h3><b>{'★'.repeat(x.rarity)}</b></div><p>{x.type} · {x.source}</p><div className="tags">{x.tags.map(t=><span key={t}>{t}</span>)}</div><div className="score">Điểm gợi ý <strong>{x.score.toLocaleString('vi-VN')}</strong></div></div></article>)}</div></section>}

function Arena(){const topics=['Thiếu nữ','Công chúa','Khu thi đấu tuần'];const [topic,setTopic]=useState(topics[0]);const rows=[...seed].sort((a,b)=>b.score-a.score).slice(0,20);return <section className="page"><div className="page-head"><div><span className="eyebrow">ARENA</span><h2>Khu Thi Đấu</h2><p>Bảng gợi ý theo thuộc tính và chủ đề.</p></div><Trophy className="big-icon"/></div><div className="pills">{topics.map(x=><button className={topic===x?'selected':''} onClick={()=>setTopic(x)} key={x}>{x}</button>)}</div><div className="arena-card"><div className="arena-title"><div><span>CHỦ ĐỀ</span><h3>{topic}</h3></div><span className="badge">Top 20</span></div>{rows.map((x,i)=><div className="rank" key={x.id}><span className="rank-no">{String(i+1).padStart(2,'0')}</span><div className="mini-art"><Sparkles size={16}/></div><div className="rank-name"><strong>{x.name}</strong><span>{x.type} · {x.tags.join(' · ')}</span></div><strong className="rank-score">{x.score.toLocaleString('vi-VN')}</strong></div>)}</div><p className="note">Điểm xếp hạng là dữ liệu tham khảo; cần đối chiếu dữ liệu game/nguồn cộng đồng trước khi sử dụng cho thi đấu thực tế.</p></section>}

function App(){const [page,setPage]=useState('home');return <Layout page={page} setPage={setPage}>{page==='home'?<Home setPage={setPage}/>:page==='database'?<Database/>:<Arena/>}</Layout>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);